Fix: fixed badword plugin
greenbone/troubadix pull request #161
Opened 2022-04-12 13:11 UTC by gb-friotte

**What**:

Updated exceptions and implemented check for file-specific exceptions 

**Why**:

Produced false positive

**How**:

**Checklist**:

- [x] Tests
- [x] Conventional commit message
- [ ] Documentation

2022-04-12 13:50 UTC, bjoernricks requested changes

2022-04-12 13:50 UTC, bjoernricks commented on troubadix/plugins/badwords.py
> +                        for _, combination in enumerate(COMBINED)
```suggestion
                        nasl_file.name == filename
                        and value in line
                        for filename, value in COMBINED
```

2022-04-13 08:51 UTC, Dexus commented
@gb-friotte please fix the linting thx

2022-04-13 09:06 UTC, bjoernricks approved these changes

2022-04-13 09:06 UTC, merged