Init standalone changed_oid
greenbone/troubadix pull request #205
Opened 2022-05-06 08:57 UTC by pascalholthaus

**What**: Draf for changed_oid plugin as standalone

**Why**:
DEVOPS-214

**How**:

**Checklist**:

- [ ] Tests
- [ ] Conventional commit message
- [ ] Documentation

2022-05-06 11:24 UTC, bjoernricks requested changes

2022-05-06 11:24 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +        print("In your current working directory is no git repository")
```suggestion
        print("Your current working directory doesn't belong to a git repository")
```

2022-05-06 11:24 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +def git(*args) -> subprocess.CompletedProcess:
```suggestion
def git(*args) -> str:
```

2022-05-06 11:24 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +    )
```suggestion
    ).stdout
```

2022-05-06 11:24 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +        ).stdout
```suggestion
        )
```

2022-05-06 11:24 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +        os.chdir(git_base.stdout.rstrip("\n"))
```suggestion
        os.chdir(git_base.rstrip("\n"))
```

2022-05-06 15:35 UTC, Dexus requested changes

2022-05-06 15:35 UTC, Dexus commented on pyproject.toml
> +troubadix-change-oid = 'troubadix.standalone_plugins.changed_oid:main'
```suggestion
troubadix-changed-oid = 'troubadix.standalone_plugins.changed_oid:main'
```

2022-05-06 15:37 UTC, Dexus requested changes

2022-05-06 15:37 UTC, Dexus commented on tests/standalone_plugins/test_changed_oid.py
> +class TestChangeOid(unittest.TestCase):
```suggestion
class TestChangedOid(unittest.TestCase):
```

2022-05-12 10:58 UTC, Dexus approved these changes

2022-05-12 14:13 UTC, n-thumann commented
I also ran this script against a branch of of the vts repo. I then changed the OID of a VT that has been modified in the previous commit, added and commited the changes.
When I now run troubadix against `HEAD^`, it will report the change, but not if run against `HEAD^^` (or `HEAD^^..HEAD`)
```
➜  vts git:(notus2nasl_for_debian_2013) troubadix-changed-oid -c HEAD^ 
Check file scripts/2013/debian/deb_2834_1.nasl
Change OID IN scripts/2013/debian/deb_2834_1.nasl OID_NEW: 1.3.6.1.4.1.25623.1.0.70283499999 OID OLD: 1.3.6.1.4.1.25623.1.0.702834
```
```
➜  vts git:(notus2nasl_for_debian_2013) troubadix-changed-oid -c HEAD^^
Check file scripts/2013/debian/deb_2389_1.nasl
[...]
Check file scripts/2013/debian/deb_2834_1.nasl
```

Is this expected?

2022-05-12 14:58 UTC, pascalholthaus commented on troubadix/standalone_plugins/changed_oid.py
> +def main(args) -> int:
Thanks there was an error with the pip installation

2022-05-13 05:57 UTC, pascalholthaus commented
I think I got it, the git filter was probably set a little too sharply.

2022-05-13 06:48 UTC, y0urself commented
> I think I got it, the git filter was probably set a little too sharply.

@n-thumann can you do us a favor and test this again?

2022-05-13 06:55 UTC, n-thumann commented
> @n-thumann can you do us a favor and test this again?

I'm already in touch with @pascalholthaus, since the issue still persists for me :)

2022-05-16 06:10 UTC, pascalholthaus commented
If you add a file in a first commit and then change it with a second commit. It may be that git diff only displays the changes made to the commit before adding the new file as a new file.

2022-05-16 08:35 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +            for _file in git(
```suggestion
            Path(f)
            for f in git(
```

2022-05-16 08:35 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +    sys.exit(main(sys.argv[1:]))
```suggestion
    sys.exit(main())
```

2022-05-16 08:35 UTC, bjoernricks commented on troubadix/standalone_plugins/changed_oid.py
> +        args = sys.argv[1:]
```suggestion
def main() -> int:
    args = sys.argv[1:]
```

2022-05-16 08:35 UTC, bjoernricks approved these changes

2022-05-16 08:36 UTC, merged