Pholthaus/deprecated functions
greenbone/troubadix pull request #225
Opened 2022-05-19 12:27 UTC by pascalholthaus

**What**: Add check_deprecated_bugtraq_id plugin.

**Why**:

**How**:

**Checklist**:

- [x] Tests
- [ ] Conventional commit message
- [ ] Documentation

2022-05-19 14:16 UTC, y0urself requested changes

2022-05-19 14:16 UTC, y0urself commented on troubadix/plugins/deprecated_bugtraq_id.py
> +# pylint: disable=fixme
```suggestion
```

2022-05-19 14:16 UTC, y0urself commented on tests/plugins/test_files/fail_bad_new_line.nasl
> +}aa
```suggestion
}

```

2022-05-19 14:18 UTC, y0urself commented
Please add a proper PR Title and sqash message.
Eg. "Add: New Plugin `CheckDeprecatedBugtraqIDTag`"

2022-05-19 14:37 UTC, cfi-gb commented
Is there a reason why this hasn't been added to the existing https://github.com/greenbone/troubadix/blob/main/troubadix/plugins/deprecated_functions.py plugin? Should be IMHO more then enough.

2022-05-20 05:40 UTC, pascalholthaus commented on tests/plugins/test_files/fail_bad_new_line.nasl
> +}aa
need to be there

2022-05-20 06:04 UTC, y0urself approved these changes

2022-05-20 06:09 UTC, pascalholthaus commented on troubadix/plugins/deprecated_bugtraq_id.py
> +# pylint: disable=fixme
file removed

2022-05-20 06:09 UTC, pascalholthaus commented on troubadix/plugins/deprecated_bugtraq_id.py
> +    name = "check_deprecated_dependency"
file removed

2022-05-20 06:11 UTC, merged