Improvement: Add spelling exemption folder for upcoming Enterprise fe…
greenbone/troubadix pull request #565
Opened 2023-05-05 11:49 UTC by js-gb

…ed files containing German language

## What
Add an additional spelling exemption folder in the Enterprise feed for German language files

## Why
Related to IT Grundschutz development.

## References
https://jira.greenbone.net/browse/VCT-239

https://github.com/greenbone/vulnerability-tests/pull/4583/files#diff-05fc57c958c392557c00b516fe7845a7eecb6205e7837bb25332a9a46e27ac8f

## Checklist

- [ ] Tests

2023-05-05 12:44 UTC, cfi-gb requested changes
If it is ever required to have the `Policy/ITG` in a folder != `gsf/`

2023-05-05 12:44 UTC, cfi-gb commented on troubadix/plugins/spelling.py
> +            "gsf/Policy/ITG/",
```suggestion
            "Policy/ITG/",
```

2023-05-05 12:44 UTC, cfi-gb commented on troubadix/plugins/spelling.py
> +        ["PCIDSS/", "GSHB/", "attic/PCIDSS_", "gsf/Policy/ITG/"], r"n[iI]n\s+==>\s+inn"
```suggestion
        ["PCIDSS/", "GSHB/", "attic/PCIDSS_", "Policy/ITG/"], r"n[iI]n\s+==>\s+inn"
```

2023-05-05 13:21 UTC, cfi-gb approved these changes

2023-05-05 13:23 UTC, cfi-gb commented
Note: The "conventional commits" action is currently failing for unknown reason (some access permission messages) and the message is actually there. We have pinged the DevOps team about this but can merge this PR anyway because i have manually verified that the commit message is there.

2023-05-08 12:19 UTC, mbrinkhoff approved these changes

2023-05-08 12:19 UTC, merged